### PR TITLE
added player model

### LINKED ISSUE #3: Import 3d player model

### PR DESCRIPTION
**Pull request by DinisSousa2003**
Alien Soldier

### CODE REVIEW

**Review by GambuzX — COMMENTED** [review]
Does a .fbx file already have the textures associated, or must they be added separately?

**Comment by DinisSousa2003** [comment]
They add to be added seperately later, thanks for the heads up! I added the textures but i didnt add the model in the right place, I'll do it again then commit it

**Comment by DoStini** [comment]
Also, under materials create a subfolder with the character name or something, so that it's more organized

**Comment by DoStini** [comment]
Maybe we can use a blender file as it all compacted into one, with bones, texture...

**Comment by GambuzX** [comment]
We have an Assets folder inside an Assets folder, what's inside can be pushed upwards
image

Also, what is the difference between the "alien mode.fbm" folder and the files inside Assets/Assets? maybe those can be removed?

**Comment by DoStini** [comment]
Yes, we can probably do that assets thing.

**Comment by DinisSousa2003** [comment]
I created the folder I think now that the model is in the right place. I did not understand what to do with the assests folder.  Is it to move the scenes and scripts out of "assests" (the first one) and then remove one of the folders, to move the folders inside the second assets folder to the first one or neither?

**Comment by GambuzX** [comment]
I was saying I think it's strange to have 2 folders called "Assets" one inside the other. What is the difference between the 2 of them?

I think that everything inside the second Assets/ folder can be placed upwards in the file tree, in the same place as the "Scenes" and "Scripts"

**Review by GambuzX — APPROVED** [review]
Looks great 👌

**Pull request merged**
